# Generated by Django 6.1.1 on 2026-10-02 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_name', models.CharField(max_length=100)),
                ('url', models.URLField(max_length=500)),
                ('price_css_selector', models.CharField(blank=True, max_length=255)),
                ('stock_css_selector', models.CharField(blank=True, max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='router.product')),
            ],
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_in_stock', models.BooleanField(default=True)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('product_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='router.productlink')),
            ],
            options={
                'ordering': ['-checked_at'],
            },
        ),
    ]
